sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t barnoldcoding/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true barnoldcoding/react-test npm test -- --coverage

after_success:
    - docker build -t barnoldcoding/multi-client ./client
    - docker build -t barnoldcoding/multi-nginx ./nginx
    - docker build -t barnoldcoding/multi-server ./server
    - docker build -t barnoldcoding/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Take those images & push them to docker hub
    - docker push barnoldcoding/multi-client
    - docker push barnoldcoding/multi-nginx
    - docker push barnoldcoding/multi-server
    - docker push barnoldcoding/multi-worker

    deploy:
        edge: true
        provider: elasticbeanstalk
        region: us-east-2
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-2-356583478594
        bucket_path: docker-multi
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
            secure: $AWS_SECRET_KEY